language: r
warnings_are_errors: false
cache: packages
r_packages:
  - covr
before_install:
  - pip install numpy --user
  - git clone https://github.com/PabRod/pendulum
  - python pendulum/setup.py install --user
after_success:
  - Rscript -e 'library(covr); codecov()'
