language: r
warnings_are_errors: false
cache: packages
r_packages:
  - covr
before_install:
  - pip install numpy --user
  - git clone https://github.com/PabRod/pendulum
  - cd pendulum
  - python setup.py install --user
  - cd ..
  - pip list
after_success:
  - Rscript -e 'library(covr); codecov()'
